<?php

namespace AppBundle\Repository;

/**
 * BilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletRepository extends \Doctrine\ORM\EntityRepository
{
    public function countNombreBillets( \DateTime $date)
    {
        return $this->createQueryBuilder('b')
            ->select('COUNT(b.nom) AS nombreBillets')
            ->where('b.dateVisite = :date')
            ->setParameter('date', $date)
            ->getQuery()
            ->getSingleResult();
    }
}
