<?php

namespace AppBundle\Repository;

/**
 * BilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletRepository extends \Doctrine\ORM\EntityRepository
{
    public function countNombreBillets( \DateTime $date)
    {
        $result = $this->createQueryBuilder('billet')
            ->select('COUNT(billet.nom) AS nombreBillets')
            ->innerJoin('billet.commande', 'commande')
            ->where('commande.dateVisite = :date')
            ->setParameter('date', $date)
            ->getQuery()
            ->getSingleResult();
        $result = (int)$result['nombreBillets'];
        return $result;
    }
}
