<?php

namespace AppBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * recherche une commande par son code de réservation
     * @param $codeReservation
     * @return bool|mixed
     */
    public function findByCodeReservation($codeReservation)
    {
        try {
            $result = $this->createQueryBuilder('commande')
                ->where('commande.codeReservation = :codeReservation')
                ->setParameter('codeReservation', $codeReservation)
                ->getQuery()
                ->getSingleResult();
        } catch (\Exception $e) {
            $result = false;
        }

        return $result;
    }
}
